// Edit this file to customize weapons
// Each weapon has: id, name, damage, fireRateMs, bulletSpeed, pelletCount, spreadDeg, color, price, magSize
export const weaponDefs = [
  {
    id: 'pistol',
    name: 'Pistol',
    damage: 15,
    fireRateMs: 220,
    bulletSpeed: 360,
    pelletCount: 1,
    spreadDeg: 0,
    maxSpreadDeg: 12,
    color: 0xffff66,
    price: 0,
    magSize: 18,
  },
  {
    id: 'railgun',
    name: 'Railgun',
    damage: 24,
    fireRateMs: 350,
    bulletSpeed: 1560,
    pelletCount: 1,
    spreadDeg: 15, // uncharged spread (deg)
    maxSpreadDeg: 0,
    color: 0x66aaff,
    price: 200,
    singleFire: true,
    magSize: 3,
    isRailgun: true,
  },
  {
    id: 'rifle',
    name: 'Rifle',
    damage: 10,
    fireRateMs: 120,
    bulletSpeed: 440,
    pelletCount: 1,
    spreadDeg: 0,
    maxSpreadDeg: 8,
    color: 0x66ccff,
    price: 60,
    magSize: 30,
  },
  {
    id: 'shotgun',
    name: 'Shotgun',
    damage: 6,
    fireRateMs: 450,
    bulletSpeed: 340,
    pelletCount: 5,
    spreadDeg: 18,
    maxSpreadDeg: 8,
    color: 0xffaa66,
    price: 80,
    magSize: 8,
  },
  {
    id: 'smg',
    name: 'SMG',
    damage: 5,
    fireRateMs: 65,
    bulletSpeed: 420,
    pelletCount: 1,
    spreadDeg: 1,
    maxSpreadDeg: 24,
    color: 0x99ff99,
    price: 90,
    magSize: 45,
  },
  {
    id: 'rocket',
    name: 'Rocket Launcher',
    damage: 40,
    fireRateMs: 700,
    bulletSpeed: 300,
    pelletCount: 1,
    spreadDeg: 0,
    color: 0xff5533,
    price: 120,
    singleFire: true,
    projectile: 'rocket',
    blastRadius: 70,
    magSize: 1,
  },
];

export const defaultWeaponId = 'pistol';

export function getWeaponById(id) {
  return weaponDefs.find((w) => w.id === id) || weaponDefs[0];
}
